version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - LOG_DIRECTORY=/var/logs
    volumes:
      - /var/log:/var/logs  # Bind mount the local code directory for easier development


